name: CommandToItem

# This will be replaced with the property "release.version" in pom.xml upon build.
version: %PLUGIN_VERSION%

main: com.leonardobishop.commandtoitem.CommandToItem
author: LMBishop
api-version: "1.13"  # enables the new material thing even though the plugin fully supports 1.8

commands:
  commandtoitem:
    description: Main command for CommandToItem
    usage: /commandtoitem
    permission: commandtoitem.admin
    aliases: [cti]

permissions:
  commandtoitem.admin:
    description: Permission for the base command
